language: ruby
rvm:
  - "1.9.3"
services:
  - mongodb
notifications:
  email:
    - jmured@gmail.com
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rspec spec